spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

logging:
  config: classpath:log4j2-test.xml
